"""Render docs/CONTINUOUS_GAIN_PHASE4E_PLAN.md: the proposed training plan for the two pilot amps, from 4A-4D data only."""
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
R = ROOT / "work" / "p4"
PILOTS = {"jcm800": "Marshall JCM800 2203 (High)", "vibrolux": "Fender Super-Sonic, Vibrolux channel"}
L = lambda a, f: json.loads((R / a / f).read_text())
T_LO, T_HI, MIN_SEP = -22.0, 14.0, 4.0
fmt = lambda s: "G" + ", G".join(f"{g:g}" for g in s)
GROUPS = ("tone EQ (dB)", "HF>3k (dB)", "crest (dB)", "dyn range (dB)", "level (dB)")

def proposed_T(SEL, sel):
    rc = SEL["response_coordinate"]; g, arc = rc["gains"], rc["arc"]
    at = lambda x: float(np.interp(x, g, arc))
    lo, hi = at(min(sel)), at(max(sel)); span = (hi - lo) or 1.0
    T = [T_LO + (T_HI - T_LO) * (at(x) - lo) / span for x in sorted(sel)]
    for _ in range(6):
        for i in range(1, len(T)): T[i] = max(T[i], T[i - 1] + MIN_SEP)
        T = [T_LO + (T_HI - T_LO) * (t - T[0]) / ((T[-1] - T[0]) or 1.0) for t in T]
    return T

def fixed_T(sel): return [T_LO + 4.0 * (g - 1.0) for g in sorted(sel)]

out = ["# Phase 4E plan (proposal to freeze): pilot on JCM800 and Super-Sonic Vibrolux\n",
"Derived only from Phase 4A-4D analysis (`CONTINUOUS_GAIN_PHASE4_QA.md`, `_PROFILES.md`, `_MAPPING.md`, `_SELECTION.md`); nothing has been trained for it. Generated by `scripts/p4_plan.py`. **Nothing below is frozen until approved**; once approved, the items in section 1 are fixed BEFORE any training and recorded with the repo commit.\n",
"## 0. Why these are the pilot amps and what the analysis says about them\n"]
plans = {}
for a, nm in PILOTS.items():
    S, T = L(a, "selection.json"), L(a, "teacher_top.json")
    ks = S["k_star_all_within_tolerance"]
    out.append(f"### {nm}\n")
    loo = S["loo_normalised_error"]; ep = S["endpoint_omitted_normalised_error"]
    inf = sorted(((sum(v.values()), k) for k, v in {**loo, **ep}.items()), reverse=True)
    out.append(f"- All 10 integer captures are VALID; no quarantine. Smallest count with every omitted position within tolerance: **k* = {ks}** (profile analysis). Most distinct positions (sum of normalised leave-one-out error): " + ", ".join(f"G{k} ({v:.2f})" for v, k in inf[:4]) + "; least distinct: " + ", ".join(f"G{k} ({v:.2f})" for v, k in inf[-3:]) + ".")
    if a == "jcm800":
        out.append("- G5 (the middle of the v3 sets) is among the least predictable-from-neighbours-free positions, i.e. the LEAST informative: its neighbours already determine it. G10 is nearly redundant with G9 (omitting it costs almost nothing). G1 and G2, where the amp changes fastest, carry the most distinct information. Near-tie to be aware of: at k=4 the rule selects G1, G2, G4, G10 (J 0.149) but G1, G2, G4, G9 is within 3% (J 0.153), and the distinctness table says G10 adds little beyond G9; the rule is applied as written so the choice is not tuned after the fact, but the tie is a fair thing to overrule before freezing.")
    else:
        out.append("- The clean-Fender behaviour is the hard case for this approach (4C: compression and level trade-offs), so a pilot here tests the method where it is weakest.")
    out.append("")
    rows = {}
    for k in sorted({3, 5, ks}):
        cs = []
        for r, c in enumerate(S["top5_by_k"][str(k)]):
            m = T["candidates"][f"k={k} rank{r+1}"]["mean"]
            cs.append({"set": c["set"], "J": c["J"], "audio": m})
        norm = {g: (np.mean([c["audio"][g] for c in cs]) or 1.0) for g in GROUPS}
        for c in cs: c["audio_score"] = float(np.mean([c["audio"][g] / norm[g] for g in GROUPS]))
        rp = {id(c): i for i, c in enumerate(sorted(cs, key=lambda c: c["J"]))}; ra = {id(c): i for i, c in enumerate(sorted(cs, key=lambda c: c["audio_score"]))}
        for c in cs: c["rank_sum"] = rp[id(c)] + ra[id(c)]
        rows[k] = sorted(cs, key=lambda c: (c["rank_sum"], c["J"]))
        out.append(f"**Candidates at k={k}** (top 5 by profile objective J, re-scored in the audio domain; combined rank = profile rank + audio rank, ties broken by J; lower is better):\n")
        out.append("| Set | J | profile rank | audio rank | audio score (rel.) | tone EQ | HF | crest | dyn range | level |"); out.append("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
        for c in rows[k]:
            out.append(f"| {fmt(c['set'])} | {c['J']:.3f} | {rp[id(c)]+1} | {ra[id(c)]+1} | {c['audio_score']:.2f} | " + " | ".join(f"{c['audio'][g]:.2f}" for g in GROUPS) + " |")
        out.append("")
    plans[a] = {"kstar": ks, "rows": rows, "S": S}

out += ["## 1. What to freeze before training (proposed)\n",
"1. **Reference dataset and quality decisions:** the 4A audit statuses in `work/p4/<amp>/audit.json` (both pilot amps: all integer captures VALID; JCM800 G8.5 half-step CORRECTED, used only as an independent check with its 692-sample shift).",
"2. **Analysis method:** `scripts/p4_profile.py`, `p4_select.py`, `p4_select_teacher.py` and the tolerances in `CONTINUOUS_GAIN_PHASE4_SELECTION.md`, at the commit recorded when frozen.",
"3. **Training positions and anchor levels** (below).",
"4. **Evaluation protocol and acceptance criteria** (below).\n",
"## 2. Proposed training positions\n",
"Rule (fixed in advance, applied to both amps): among the top-5 profile-ranked sets at the amp's k*, take the lowest combined (profile + audio-domain) rank; ties by J. An amp-specific k* is used instead of an imposed count. For comparability with earlier work a 3-capture set chosen by the SAME rule is included as a budget candidate.\n",
"| Amp | primary (k*) | budget (k=3, same rule) | 5-capture reference (same rule) |", "|---|---|---|---|"]
for a, nm in PILOTS.items():
    p = plans[a]; ks = p["kstar"]
    out.append(f"| {nm} | {fmt(p['rows'][ks][0]['set'])} (k={ks}) | {fmt(p['rows'][3][0]['set'])} | {fmt(p['rows'][5][0]['set'])} |")
out += ["", "## 3. Proposed input-gain anchors\n",
"Two anchor rules, so capture placement and gain mapping are never conflated:\n",
"- **fixed** (v3 rule): a capture at knob position N sits at input gain `-22 + 4(N-1)` dB.",
f"- **response-distance** (revised mapping): anchors placed along the amp's measured response coordinate (arc length of the normalised tone+saturation+compression profile over ALL validated captures, level excluded), range {T_LO:+.0f} to {T_HI:+.0f} dB like v3, at least {MIN_SEP:.0f} dB between anchors so adjacent captures stay separable by level. Uses only measured captures; no NAM, no held-out DI.\n",
"| Amp | set | fixed (dB) | response-distance (dB) |", "|---|---|---|---|"]
for a, nm in PILOTS.items():
    p = plans[a]
    for lab, sel in (("primary", p["rows"][p["kstar"]][0]["set"]), ("budget k=3", p["rows"][3][0]["set"])):
        out.append(f"| {nm} | {lab}: {fmt(sel)} | " + ", ".join(f"G{g:g} {x:+.0f}" for g, x in zip(sorted(sel), fixed_T(sel))) + " | " + ", ".join(f"G{g:g} {x:+.1f}" for g, x in zip(sorted(sel), proposed_T(p["S"], sel))) + " |")
out += ["",
"## 4. Proposed 2x2 design per pilot amp (separates placement from mapping)\n",
"| Model | positions | anchor rule | answers |", "|---|---|---|---|",
"| v3 C3 (existing, not retrained) | G1, G5, G10 | fixed | baseline; also evaluated with the revised mapping (playback only) = the mapping-only baseline from 4C |",
"| P-fixed | primary set | fixed | effect of capture PLACEMENT alone (vs v3 C3, same anchor rule) |",
"| P-resp | primary set | response-distance | effect of MAPPING on top of placement (vs P-fixed) |",
"| B-resp (optional) | budget k=3 set | response-distance | does an adaptively chosen 3 suffice? (vs v3 C3, and vs P-resp) |\n",
"Same architecture (A2), 60 epochs, same trainer and data recipe as v3 (467 s of official input + DI material at four level offsets). Two seeds each for P-fixed and P-resp so that seed noise can be compared with any claimed difference. Real training duration is recorded per model (v3 measured about 18-24 minutes per model when two to six run concurrently on this machine).\n",
"## 5. Evaluation protocol and acceptance criteria (proposed, to be frozen)\n",
"- **Independent material:** held-out DIs moderate_brit, clean_mayer, bass_rollin (never used in any fit); on the JCM800 the 9 genuine half-steps; on the Vibrolux there are no half-steps, so the untrained integer captures serve as untouched positions, with the caveat that they were used in the selection analysis (4D), so they are not fully independent.",
"- **Measures, reported separately:** tone EQ, HF>3 kHz, crest, sine THD, input/output slopes, dynamic range, output level (as in 4C), at DI levels -12/-6/0/+6 dB; level-matched ESR only as a supporting number.",
"- **Success (all must hold, versus v3 C3 with the fixed anchors, on held-out DIs and untouched positions):** (a) tone, HF and crest errors not worse by more than 10%; (b) input/output slope and dynamic-range errors each reduced by at least 15% for P-resp; (c) level error within 1.5 dB; (d) no group worse by more than 25% at any tested DI level; (e) the difference is larger than the seed-to-seed spread of the two seeds.",
"- **Interpretation rules:** an improvement that appears only with the revised mapping is a mapping result, not a placement result; a metric win without the listening set is a technical result, not an audible one; if the C3 budget candidate fails, report the failing behaviour and whether extra captures are a justified next step rather than adding them automatically.",
"- **Exported `.nam` requirement:** standard A2, playable in an ordinary player with input gain only; any improvement that needs extra DSP or metadata is reported separately.\n",
"## 6. Known risks to state before running\n",
"- Selection and mapping both use the same measured captures the models are later scored on; the held-out DIs and (JCM800) half-steps are the only fully independent material.",
"- 4C showed compression mismatch survives even the best mapping and looks like a limit of the level-driven design; expect P-resp to help that dimension only partly, and on the Vibrolux possibly at the cost of output level.",
"- The waveform-blend teacher has its own floor (about 1 dB of HF error even with five captures on the JCM800), which no choice of positions removes.",
"- One machine, one architecture, single-seed v3 baselines."]
(ROOT / "docs" / "CONTINUOUS_GAIN_PHASE4E_PLAN.md").write_text("\n".join(out))
for a in PILOTS: print(a, {k: (fmt(v[0]["set"])) for k, v in plans[a]["rows"].items()})
