"""Compose docs/CONTINUOUS_GAIN_TONAL_REFINEMENT.md from work/tr/{analysis,ir_analysis}.json and work/tr/audition/manifest.json."""
import json, subprocess
from pathlib import Path
REPO = Path(__file__).resolve().parent.parent; A = json.loads((REPO / "work/tr/analysis.json").read_text()); I = json.loads((REPO / "work/tr/ir_analysis.json").read_text()); M = json.loads((REPO / "work/tr/audition/manifest.json").read_text())
NAME = {"jcm800": "Marshall JCM800 2203 (High)", "vibrolux": "Fender Super-Sonic Vibrolux"}; commit = subprocess.check_output(["git", "-C", str(REPO), "rev-parse", "--short", "HEAD"], text=True).strip()
o = ["# Continuous Gain: tonal refinement (measurements and audition package)\n", f"Branch `research/continuous-gain-model`, code at `{commit}` plus the `scripts/tr_*.py` files added here. No model was trained, and no frozen result, capture or model export was changed. Outputs are under `work/tr/` (measurements, audition WAVs) and `docs/tonal/` (plots).\n"]
o += ["## Summary\n",
 "**Answer to the central question: a modest static EQ does not improve the whole virtual amplifier for either amp, so none should go into the NAM yet.**\n",
 "- **Marshall JCM800.** The native FC model is already spectrally very close to the real captures. At G10 the largest level-independent error on held-out DIs is -0.7 dB at 12.7 kHz and -0.4 dB over 4-10 kHz (FC slightly duller). The error changes sign across the sweep (G2 is up to +1.2 dB too bright at 12.7 kHz (+2.9 dB on the fit DIs), G4-G10 are up to 1.4 dB too dull at 12.7 kHz), so an EQ fitted across the sweep comes out at 0.3 dB or less. That is far below what is audible. **The measured native tone does not explain the 'less open and full' G10 you hear after CLO and an IR.** With the repo test IR the spectral difference is unchanged (0.20 dB mean absolute band error native, 0.20 dB with the IR), because a cabinet IR is linear and cannot create a spectral difference. The CLO stage could not be tested (see below), so the cause is unresolved.",
 "- **Fender Vibrolux.** There is a real, consistent tonal error, but only at the clean positions: G1-G3 are 0.6-1.5 dB too full at 80-800 Hz and 1-7 dB too dark above 5 kHz (worst at 12.7 kHz), on every DI, every level and both seeds, but the two FC seeds differ (HF at G1: 4 dB apart). G7-G10 are within 0.8 dB in every band. A static EQ that fixes the clean sound (candidate B) adds +1.6 dB of HF error at crunch and saturated positions and roughly triples the G9-G10 band error. A gain-dependent curve would be needed, which the brief rules out for now. The clean-end darkness is a training limitation of these FC seeds, not an EQ problem.",
 "- **Recommendation.** Keep the existing FC models. Do not retrain for tone yet. If the Marshall G10 fullness difference persists, do the CLO/IR isolation protocol in section 2 first, because the native NAM does not show it.\n"]
o += ["## 1. Source identities\n", "- Real references: the original fixed-gain NAM captures, rendered with NAMCore (`native/nam_render`) and the verified Phase 4A alignment (no corrections were needed for the pilot captures). JCM800 integer positions G1-G10 (the half-steps were not used here); Vibrolux G1-G10 integers.",
 "- Models: `deliverables/<amp>/alt_FC_s0.nam` and `alt_FC_s1.nam` (FC seeds 0 and 1, frozen at `99ca9b6`, trained at `work/p4e/final/<amp>/FC_bundle/`); output scale c from each bundle manifest (JCM800 0.7219, Vibrolux 1.0). No output-gain change was applied.",
 "- Mapping: the frozen FC anchor mapping (JCM800 G1/G2/G4/G10 at -20/-9.2/-1.7/+14 dB; Vibrolux G1/G2/G3/G4/G7/G10 at -20/-15.6/-7.1/-2.2/+5.7/+14 dB) with position-to-Input-gain interpolation in the response coordinate. It was not refitted per DI or gain. Intended Input gain per position is in the tables below.",
 "- DIs: held-out `moderate_brit`, `clean_mayer`, `bass_rollin` at -12/-6/0/+6 dB for all evaluation; fit DIs `clean_smooth`, `moderate_hotrod`, `high_thrash`, `high_metalcore` at -6/0 dB for EQ fitting only.\n"]
o += ["## 2. Native NAM versus CLO conversion and IR: status\n", "| Stage | Status |", "|---|---|",
 "| Original .nam vs FC .nam, no cab/CLO/EQ | **Done** (section 3) |",
 f"| Same signals through the repo test IR (`{I['ir']}`) | **Done, analytically.** An IR is a linear filter, so it multiplies both spectra by the same |IR|^2. Mean absolute band error, native vs with IR: JCM800 G1 {I['jcm800']['1']['native_mean_abs']:.2f} vs {I['jcm800']['1']['IR_mean_abs']:.2f} dB, G5 {I['jcm800']['5']['native_mean_abs']:.2f} vs {I['jcm800']['5']['IR_mean_abs']:.2f}, G10 {I['jcm800']['10']['native_mean_abs']:.2f} vs {I['jcm800']['10']['IR_mean_abs']:.2f}. HF 4-10 kHz at G10: {I['jcm800']['10']['native_hf_4_10k']:+.2f} vs {I['jcm800']['10']['IR_hf_4_10k']:+.2f} dB. **This is not your IR**; it is the test IR shipped in `assets/nam_models`. So the IR does not increase the spectral difference, but a different IR could weight the region differently by at most the small errors above. |",
 "| Original capture -> CLO -> IR vs FC -> CLO -> IR | **Pending: the converter is not in this codebase** (NAMtoClo is a separate project; this repository shares no code with it). No substitute IR or converter was treated as your setup. |\n",
 "Protocol for the pending stage (to run once the converter and your IR are at hand): (1) render one DI (`moderate_brit`, offset 0) through the original G10 `.nam` and through `alt_FC_s0.nam` at its intended G10 setting (+14 dB Input gain, output gain +2.8 dB for the JCM800 FC model, see `docs/CONTINUOUS_GAIN_FINAL_CANDIDATES.md`) with **no** cab; (2) convert both to CLO with identical settings, including whatever input-level calibration and output level the converter applies, and note that a converted model normally has a **fixed input level, so the +14 dB virtual gain must be reproduced by adding the gain in the DI** before conversion or by a comparable gain stage, otherwise the FC model is playing at the wrong virtual gain; (3) render the same DI through both CLOs with the identical IR at identical output level; (4) run `scripts/tr_measure.py`-style band analysis on the WAVs. If the FC-vs-original difference appears only at step 3, it comes from CLO conversion (or its gain staging); if it is already in step 1, it is the NAM. That gain-staging point is a hypothesis, not a finding.\n"]
o += ["## 3. Tonal difference across the whole gain sweep (native NAM, held-out DIs)\n", "Method: NAMCore renders of each held-out clip at every DI level; average power spectra over Hann-windowed 2048-sample frames (hop 512), the first 0.5 s and frames more than 55 dB below the loudest frame dropped, so silence and noise floor never enter; 1/3-octave bands 50 Hz to 12.7 kHz; frames classified from the REAL signal into attack (rising at least 4 dB over the preceding 43 ms), decay (falling at least 4 dB) and sustain. **Signed convention: FC minus real. Positive means FC has MORE energy in that band than the real amp; negative means FC has LESS.** Level-independent errors have the mean difference over 200-6400 Hz removed; the native output-level error is reported separately.\n", "Plots: `docs/tonal/tonal_heatmap_<amp>.png` (position by band), `tonal_curves_<amp>.png` (by position, playing phase, input level), `tonal_broad_<amp>.png` (broad bands, HF share, tilt, native level), `tonal_eq_<amp>.png` (candidates).\n"]
for amp, d in A.items():
    t = d["signed_table"]; o += [f"### {NAME[amp]}\n", f"![heatmap](tonal/tonal_heatmap_{amp}.png)\n", f"![curves](tonal/tonal_curves_{amp}.png)\n", f"![broad](tonal/tonal_broad_{amp}.png)\n",
        "| Position | Input gain (dB) | low 80-250 | low-mid 250-630 | mid 630-1.6k | upper-mid 1.6-4k | high 4-10k | HF>3k share | tilt (dB/oct) | native level err (dB) | seed spread, high band |", "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|"]
    for g in d["gains"]:
        a = t[f"{g:g}"]["all"]; o.append(f"| G{g:g} | {d['T'][f'{g:g}']:+.1f} | " + " | ".join(f"{a[k]:+.2f}" for k in ("low 80-250", "low-mid 250-630", "mid 630-1.6k", "upper-mid 1.6-4k", "high 4-10k", "HF>3k share", "tilt dB/oct")) + f" | {t[f'{g:g}']['native_level_rms_db']:+.2f} | {t[f'{g:g}']['seed_diff_hf_db']:.2f} |")
    o += ["", "By playing phase at the top and clean ends (high 4-10 kHz signed error, dB; n = number of DI/level/seed cases with enough frames):\n", "| Position | all | attack | sustain | decay |", "|---|---:|---:|---:|---:|"]
    for g in (d["gains"][0], d["gains"][len(d["gains"]) // 2], d["gains"][-1]):
        r = t[f"{g:g}"]; o.append(f"| G{g:g} | " + " | ".join((f"{r[c]['high 4-10k']:+.2f}" if c in r else "-") for c in ("all", "attack", "sustain", "decay")) + " |")
    o += ["", "By musical input level (HF>3k share error, dB):\n", "| Position | " + " | ".join(f"{k} dB DI" for k in t[f"{d['gains'][0]:g}"]["by_offset_hf_share"]) + " |", "|---|" + "---:|" * 4]
    for g in (d["gains"][0], d["gains"][len(d["gains"]) // 2], d["gains"][-1]): o.append(f"| G{g:g} | " + " | ".join(f"{v:+.2f}" for v in t[f"{g:g}"]["by_offset_hf_share"].values()) + " |")
    o.append("")
o += ["Reading the result: the JCM800 errors are small at every position and change sign (G2 bright, G4-G10 slightly dull); the decay phase carries the largest HF shortfall at high gain (-2 to -8 dB above 5 kHz at G10, but from few, quiet frames, so it is noisy), which no static EQ addresses without also changing the sustain. The Vibrolux error is large, consistent and only at G1-G3, and it depends on the seed. Distortion texture, compression and transient behaviour are not captured by a long-term spectrum, so a spectrum that matches within 0.5 dB does not prove the sounds are identical.\n"]
o += ["## 4. EQ candidates (fitted without training, on the fit DIs at the FC anchor positions only)\n", "Structure: low shelf, one peaking band, high shelf (RBJ biquads, causal minimum-phase IIR, 48 kHz), so at most 3 sections. Limits: each band within +-3 dB (B) or +-4 dB (C), peak Q 0.5-1.5, shelf slope 0.7, small gain penalty in the fit, and the fit ignores overall level so the EQ does not change loudness by design. Reason: the measured errors are at most a few dB and only a broad correction can generalise across DIs. A: no EQ (existing FC). C is the same fit with the top anchor positions weighted 3x to favour the high-gain sound.\n"]
for amp, d in A.items():
    o += [f"### {NAME[amp]}\n", "| Candidate | Section | Type | Freq (Hz) | Gain (dB) | Q / slope | Max boost / cut in the audio band (dB) | Max group delay (ms) |", "|---|---|---|---:|---:|---:|---|---:|"]
    for n in ("B", "C"):
        e = d["eq"][n]
        for i, p in enumerate(e["params"]): o.append(f"| {n} | {i + 1} | {p['type'].replace('_', ' ')} | {p['f']:.0f} | {p['gain_db']:+.2f} | {p.get('q', p.get('s')):.2f} | " + (f"{e['max_gain_db']:+.2f} / {e['max_cut_db']:+.2f} | {e['group_delay_max_ms_below_12k']:.3f} |" if i == 0 else " | |"))
    o += ["", "Latency and phase: the filters are causal biquads with no look-ahead (zero added latency in a plugin), and the group delay above is the worst-case delay across sections below Nyquist/2, well under 0.1 ms. Headroom: the maximum boost above is the worst-case peak increase; time-domain peaks measured at the hardest musical input (+6 dB DI, no cab) are in the table below."]
    if amp == "jcm800": o.append("JCM800 candidate B is a fit result of at most 0.3 dB; C is +0.27 dB above 2.9 kHz. Both are inaudible in isolation.")
    o.append("")
o += ["Time-domain peak check (dBFS, no cab, +6 dB DI):\n", "| Amp | Position | real | FC | FC + B | FC + C |", "|---|---|---:|---:|---:|---:|"]
for amp, m in M.items():
    for k, v in m["time_domain_peaks_hard_+6dB_no_cab_dbfs"].items(): o.append(f"| {amp} | {k} | {v['real_peak_dbfs']:.1f} | {v['FC_peak_dbfs']:.1f} | {v['FC_B_peak_dbfs']:.1f} | {v.get('FC_C_peak_dbfs', float('nan')):.1f} |")
o += ["\nCandidate C for the JCM800 is not built into the audition set: at 0.27 dB it does not differ audibly from B. The Vibrolux C is included because it is the only candidate that trades clean-end improvement against crunch regression differently.\n"]
o += ["## 5. Validation across the amplifier (held-out DIs, all positions, both seeds)\n", "Measure: mean absolute 1/3-octave error from 80 Hz to 12.7 kHz (level-independent), separately for the whole clip, the attack phase and the decay phase; signed 4-10 kHz error and tilt; the level shift the EQ adds (the native output-level progression must not change). Regions: clean G1-2, edge G3-4, crunch G5-8, saturated G9-10. 'Intermediate positions' are the ones not used for the fit; 'anchors' are the fitted positions.\n"]
for amp, d in A.items():
    v = d["validation"]; o += [f"### {NAME[amp]}\n", "| Region | Cand. | mean abs band err | attack | decay | signed 4-10k | tilt (dB/oct) | EQ level shift (dB) |", "|---|---|---:|---:|---:|---:|---:|---:|"]
    for rn in d["regions"]:
        for n in ("A_no_EQ", "B", "C"):
            r = v[n].get(rn)
            if r: o.append(f"| {rn} | {n} | {r['mean_abs_band_err_db']:.2f} | {r['attack_mean_abs_db']:.2f} | {r['decay_mean_abs_db']:.2f} | {r['high 4-10k']:+.2f} | {r['tilt_db_oct']:+.2f} | {r['level_shift_from_EQ_db']:+.2f} |")
    o.append("")
o += ["Interpretation:\n",
 "- **JCM800:** B and C reduce the mean absolute band error by 0.02-0.07 dB (0.27 to 0.20 at saturated G9-G10). The signed 4-10 kHz shortfall at G10 only goes from -0.44 to -0.26 dB (C). There is no regression in any region and the level shift is constant (B -0.19 dB, C +0.06 dB), so the progression is not changed, but the gain is too small to matter, and attack and decay errors are unchanged. The reported openness difference is therefore not something these EQs address.",
 "- **Vibrolux:** B improves the clean region (1.78 to 0.96 dB) and the edge region, but doubles or triples the error at crunch (0.73 to 1.12) and saturated (0.33 to 0.94), turns the 4-10 kHz error at G5-G10 into +1.6 dB (too bright), and shifts native level by -1 dB. C is a smaller version of the same trade-off (saturated 0.33 to 0.67). **Neither passes the criterion that the rest of the amp must not get noticeably worse**, and the decay-phase error worsens (1.6 to 2.4 dB at crunch with B).",
 "- Both fits were made on the fit DIs and tested on different held-out DIs at positions not used for fitting; the conclusions are the same on the anchors and the intermediate positions.\n"]
o += ["## 6. Audition package\n", "Location: `work/tr/audition/<amp>/` (WAV, 24-bit, 48 kHz, 15 s clips; not committed because of size), file list in `work/tr/audition/manifest.json`. Non-blind by design (the purpose is to hear what the EQ changes), so beware expectation bias.\n",
 f"- **JCM800** ({M['jcm800']['di']}, normal level): real, FC no EQ (A), FC + EQ B at G1, G2, G5, G8, G10, native and level-matched, through the repo test IR (`{M['jcm800']['ir']}`, not your IR); plus G10 with no IR. The G10 files are the comparison that prompted this work.",
 f"- **Vibrolux** ({M['vibrolux']['di']}, normal level): real, A, B and C at G1, G3, G5, G7, G10, both level modes, with the test IR; plus G10 without IR; and FC seed 1 (no EQ) at G1 and G3 because the seeds differ most on the clean tone.",
 f"- Native files share one output gain per amp/IR setting (JCM800 IR set {M['jcm800']['native_common_gain_IR']:.3f}, Vibrolux IR set {M['vibrolux']['native_common_gain_IR']:.3f}) so the peaks are at most -1 dBFS; level-matched files equal the real capture's active-material RMS.",
 "- Filter settings for a live plugin test are in the tables of section 4 (low shelf / peak / high shelf; slope 0.7 shelves). In a normal parametric EQ, the JCM800 candidate B is the three settings listed, all within -0.3 dB, so for a live test use a brighter, deliberately audible probe (for example +1.5 dB high shelf at 5 kHz) rather than B to learn what it would take to hear a difference. That probe is a listening aid, not a candidate.",
 "- Nothing measured here is claimed as audible until you have listened.\n"]
o += ["## 7. Recommendation and smallest next step\n",
 "1. **Do not add a post-NAM EQ to the FC models** and do not retrain with a corrected teacher: for the JCM800 the correction is inaudible and mixed in sign, and for the Vibrolux a static curve fixes the clean sound at the cost of the crunch and saturated sounds.",
 "2. **First find where the reported Marshall difference comes from.** Run the section 2 protocol (needs the CLO converter and your IR). If it is CLO gain staging (the +14 dB virtual gain not reproduced), that is a workflow fix, not a model fix.",
 "3. **If the difference is audible in the native audition WAVs**, it is not in the long-term spectrum, and the next measurement should look at harmonic distortion at low levels, the decay tails (the only place the JCM800 error exceeds 2 dB) and transients, not at EQ.",
 "4. **The Vibrolux clean-end darkness (G1-G3, seed dependent)** is a real finding for the training side (for example clean-anchor weighting or seed choice), separate from this request and not to be attempted until you decide.\n",
 "Limitations: one listener, no human listening on the EQ candidates yet, held-out spectra are long-term averages, and the repo IR is not your IR."]
(REPO / "docs" / "CONTINUOUS_GAIN_TONAL_REFINEMENT.md").write_text("\n".join(o) + "\n"); print("written")
